### ISSUE TITLE
Can you write a doc

### ISSUE THREAD

**Issue by louisthomaspro** [egs33/laravel-datastore-auth#1]
Hi,
You did a great job ! I would like to use your component in my project. Can you write a doc pls, because I'm stuck.
Thanks !

**Comment by egs33** [comment]
I wrote document.

But my English is poor. If you cant understand, please tell me.

**Comment by louisthomaspro** [comment]
You're awesome, it works great !!
Thanks you ;)

**Comment by louisthomaspro** [comment]
Did you handle the session cache on laravel with datastore ? (you can contact my by hangout)
